"""Bundle the engine, the weights and the app into dist/.

The engine is written as ES modules so node:test can import individual kernels,
but the deployed page must not fetch anything. This step resolves that by
concatenating the modules in dependency order, stripping the import/export
syntax, and embedding the worker as a string that the app turns into a Blob URL
at runtime.

Output is two files:

    dist/index.html
    dist/hotdog.js     engine + int8 weights + worker source + app

Nothing else is fetched, ever, except the sample thumbnails — and only if
somebody clicks one.
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from common import DIST, ROOT

ENGINE = ROOT / "engine"
WEB = ROOT / "web"

# Dependency order. fixedpoint has no imports; kernels needs fixedpoint;
# model needs kernels.
MODULES = ["fixedpoint.js", "kernels.js", "model.js"]

IMPORT_RE = re.compile(r"^\s*import\s.*?from\s+['\"].*?['\"];?\s*$", re.M)
EXPORT_RE = re.compile(r"^(\s*)export\s+(?=(?:const|function|class|let|var)\b)", re.M)


def strip_module_syntax(src: str) -> str:
    src = IMPORT_RE.sub("", src)
    src = EXPORT_RE.sub(r"\1", src)
    if "export " in src or re.search(r"^\s*import\s", src, re.M):
        raise SystemExit("unhandled module syntax survived stripping")
    return src


def main() -> None:
    model_js = DIST / "model.js"
    if not model_js.exists():
        sys.exit("missing dist/model.js — run train/export.py first")

    parts: list[str] = [
        "// Not Hotdog — https://github.com/EricSpencer00/not-hotdog",
        "// Generated by build.py. Engine sources live in engine/.",
        "// No dependencies. No network requests. Nothing leaves your device.",
    ]

    engine_src = "\n".join(
        strip_module_syntax((ENGINE / m).read_text()) for m in MODULES
    )
    weights_src = strip_module_syntax(model_js.read_text())
    worker_src = WEB.joinpath("worker-src.js").read_text()

    # The worker gets the engine, the weights and its own glue, as one string.
    worker_bundle = "\n".join([weights_src, engine_src, worker_src])
    parts.append(
        "const WORKER_SOURCE = "
        + _js_string(worker_bundle)
        + ";"
    )
    parts.append(WEB.joinpath("app.js").read_text())

    out = "\n".join(parts) + "\n"
    (DIST / "hotdog.js").write_text(out)

    shutil.copy(WEB / "index.html", DIST / "index.html")
    samples_src = WEB / "samples"
    samples_dst = DIST / "samples"
    if samples_src.exists():
        if samples_dst.exists():
            shutil.rmtree(samples_dst)
        shutil.copytree(samples_src, samples_dst)

    html = (DIST / "index.html").stat().st_size
    js = (DIST / "hotdog.js").stat().st_size
    samples = sum(f.stat().st_size for f in samples_dst.glob("*")) if samples_dst.exists() else 0

    print(f"dist/index.html   {html / 1024:7.1f} KB")
    print(f"dist/hotdog.js    {js / 1024:7.1f} KB")
    print(f"critical path     {(html + js) / 1024:7.1f} KB   (no other requests)")
    print(f"samples (lazy)    {samples / 1024:7.1f} KB   (fetched only on click)")
    if html + js > 250 * 1024:
        print("!! over the 250 KB budget in SPEC.md §1 C5")


def _js_string(s: str) -> str:
    """Embed arbitrary JS as a string literal safely."""
    esc = (
        s.replace("\\", "\\\\")
        .replace("`", "\\`")
        .replace("${", "\\${")
    )
    return "`" + esc + "`"


if __name__ == "__main__":
    main()
